import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { Inter } from 'next/font/google';
import './globals.css';
import { ReduxProvider } from '@/providers/redux.provider';
import NavBar from '@/components/shared/navbar';
import { SessionProvider } from 'next-auth/react';
import SessionsProvider from '@/providers/session.provider';


const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900'
});
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <SessionsProvider>
            <html lang="en">
            <ReduxProvider>
                <body className={inter.className}>
                <NavBar></NavBar>
                    {children}
                </body>
                </ReduxProvider>
            </html>
        </SessionsProvider>
    );
}
